// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Play.Catalog.Service.Data;

#nullable disable

namespace Play.Catalog.Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240513133317_SeedCouponTables")]
    partial class SeedCouponTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Play.Catalog.Service.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e049de7-4ea3-464c-a4e1-c365578a4743"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 5, 13, 18, 33, 16, 854, DateTimeKind.Unspecified).AddTicks(2576), new TimeSpan(0, 5, 0, 0, 0)),
                            Description = "New Item",
                            Name = "Some name",
                            Price = 1.2m
                        },
                        new
                        {
                            Id = new Guid("fe45d474-97df-45ac-aa28-711b4d86eff5"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 5, 13, 18, 33, 16, 854, DateTimeKind.Unspecified).AddTicks(2628), new TimeSpan(0, 5, 0, 0, 0)),
                            Description = "New Item2",
                            Name = "Some name2",
                            Price = 1.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
